all: freq.exe

# Change PREFIX to choose where to install files
PREFIX=${HOME}

# If you have nonstandard utilities in non-standard places,
# change thse variables:
CC=cc
STRIP=strip
MV=mv
MKDIR=mkdir
CP=cp

freq.exe: freq.c
	${CC} -std=c11 -O3 -o freq freq.c
	${STRIP} freq.exe

clean:
	-${RM} *~ *.o freq.exe

install: all
	${MKDIR} -p ${PREFIX}/bin
	${MV} freq.exe ${PREFIX}/bin
	${MKDIR} -p ${PREFIX}/man/man1
	${CP} freq.1 ${PREFIX}/man/man1
