all: freq

# Change PREFIX to choose where to install files
PREFIX=${HOME}

# If you have nonstandard utilities in non-standard places,
# change thse variables:
CC=cc
STRIP=strip
MV=mv
MKDIR=mkdir
CP=cp

freq: freq.c
	${CC} -std=c11 -O3 -march=native -o freq freq.c
	${STRIP} freq

clean:
	-${RM} *~ *.o freq

install: all
	${MKDIR} -p ${PREFIX}/bin
	${MV} freq ${PREFIX}/bin
	${MKDIR} -p ${PREFIX}/man/man1
	${CP} freq.1 ${PREFIX}/man/man1
